[package]
authors = ["tubackkhoa"]
edition = "2018"
name = "cosmwasm-simulate"
version = "0.13.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]

[dependencies]
base64 = "0.13.0"
clap = "~2.32"
cosmwasm-std = "0.13.0"
cosmwasm-vm = "0.13.0"
lazy_mut = "0.1.0"
rustyline = "8.0.0"
serde = {version = "1.0.103", default-features = false, features = ["derive", "alloc"]}
serde_json = "1.0"
ureq = "2.0.2"
wasmer-middleware-common = "0.17"
wasmer-runtime-core = "0.17"
wasmer-singlepass-backend = "0.17"
